export const UPDATE_CHARACTERS_LIST = '@characters/UPDATE_CHARACTERS_LIST';
export const UPDATE_CHARACTERS_LOADING = '@characters/UPDATE_CHARACTERS_LOADING';
export const UPDATE_CHARACTERS_ITEM = '@characters/UPDATE_CHARACTERS_ITEM';
export const ADD_NEW_CHARACTER = '@characters/ADD_NEW_CHARACTER';